branch-defaults:
  develop:
    environment: heycoach-api-dev
environment-defaults:
  heycoach-api-dev:
    branch: null
    repository: null
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: hc-dev-api
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Tomcat 8 with Java
    8 running on 64bit Amazon Linux/2.6.1
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: ./target/api-1.0.0.war
